### ISSUE TITLE
Typo in /etc/pam.d/gnome-screensaver

### ISSUE THREAD

**Issue by tylerj2050** [RedHatGov/ssg-el6-kickstart#8]
Hello, 

I have been using the ssg-el6-kickstart for a hardened baseline build for a few years now with great results. I noticed one small issue with the latest release that is easily fixed: 

When operating in runlevel 5 I was unable to log back in to the machine once it reached the lock screen. After unsuccessfully trying a few fixes I noticed a sequence in /var/log/secure that pointed the culprit out. 

Aug 15 16:35:32 XXX gnome-screensaver-dialog: PAM (gnome-screensaver) illegal module type: %PAM-1.0
Aug 15 16:35:32 XXX gnome-screensaver-dialog: PAM (gnome-screensaver) no control flag supplied
Aug 15 16:35:32 XXX gnome-screensaver-dialog: PAM (gnome-screensaver) no module name supplied

The first line of /etc/pam.d/gnome-screensaver should be "#%PAM-1.0" instead of "%PAM-1.0". Looks to have the typo in ipa-pam-configuration.sh also. 

Otherwise everything else is excellent. I hope this helps.

**Comment by fcaviggia** [comment]
Thanks - I will add that fix right now,

**Comment by fcaviggia** [comment]
Updated. Thanks for the catch.
