### ISSUE TITLE
Remote Desktop not working at all, Am I missing something in the config scripts?

### ISSUE THREAD

**Issue by Criticize** [RedHatGov/ssg-el6-kickstart#9]
For the life of me, I cannot seem to figure out how to make Remote Desktop / XRDP work. I have tried everything I can find, performed multiple re-installs, along with different workstation types. But nothing seems to change the fact that I cannot connect to the hardened workstation via remote desktop.

**Note** I have managed to get the hardening script to work with CentOS 6.8 without issue or error during the installation.

I've tested my procedure of setting up Remote Desktop / XRDP on an unhardened instance and it works without issue but to no avail it will not work with the hardened image.

Am I missing something within the hardening configuration scripts that is preventing the ability for me to remote desktop into the machine? 

Any insight or assistance someone could lend would be greatly appreciated!

**Comment by stephenwb** [comment]
It would help if you detailed your procedure. For example, unless you're connecting via ssh and setting up a tunnel for the XRDP port (3389) prior to attempting to connect via XRDP, it's going to fail because the hardening turns on the firewall and blocks all but port 22.

**Comment by stephenwb** [comment]
Suggest closing this @fcaviggia since @Criticize hasn't followed up.

**Comment by fcaviggia** [comment]
@Criticize - there is an SELinux issue with XRDP that I had to change here:

/usr/bin/chcon -t bin_t /sbin/xrdp*
